export const ADD_NEW_BADGE = "ADD_NEW_BADGE";
export const ADD_BADGE = "ADD_BADGE";
export const BADGE_SELECTED = "BADGE_SELECTED";
export const BADGE_UNSELECTED = "BADGE_UNSELECTED";
export const CLEAR_CURRENT_BADGE_LIST = "CLEAR_CURRENT_BADGE_LIST";
export const POP_BADGE_FROM_CURRENT = "POP_BADGE_FROM_CURRENT";
