export const TOGGLE_KEYDOWN_SELECT = "TOGGLE_KEYDOWN_SELECT";
export const TOGGLE_KEYUP_SELECT = "TOGGLE_KEYUP_SELECT";
export const RESET_TOGGLE_KEYDOWN = "RESET_TOGGLE_KEYDOWN";
export const RESET_TOGGLE_KEYUP = "RESET_TOGGLE_KEYUP";
